// inject-env.cjs
const fs = require('fs');
const path = require('path');

function safeJsonParse(s, def = null) {
  try { return JSON.parse(s); } catch { return def; }
}

function envOrThrow(name, { optional = false } = {}) {
  const v = process.env[name];
  if (!v && !optional) throw new Error(`Missing ENV: ${name}`);
  return v || '';
}

function buildVersion() {
  // prova a leggere la SHA da Vercel oppure timestamp
  const sha = process.env.VERCEL_GIT_COMMIT_SHA || process.env.GIT_COMMIT_SHA || '';
  if (sha && /^[0-9a-f]{7,}$/.test(sha)) return sha;
  return String(Date.now());
}

try {
  const FIREBASE_CONFIG_JSON = process.env.FIREBASE_WEB_CONFIG || process.env.FIREBASE_CONFIG || '';
  const FIREBASE_ENABLED = String(process.env.FIREBASE_ENABLED || 'true').toLowerCase() !== 'false';

  const WHATSAPP_API_BASE = process.env.WHATSAPP_API_BASE || 'https://remindertribu-two.vercel.app/api';
  const REMINDER_DAYS_AHEAD = parseInt(process.env.REMINDER_DAYS_AHEAD || '7', 10);
  const GOOGLE_CALENDAR_EMBED_URL = process.env.GOOGLE_CALENDAR_EMBED_URL || '';

  const fbConfigObj = safeJsonParse(FIREBASE_CONFIG_JSON, null);
  if (!fbConfigObj) {
    console.warn('⚠️ FIREBASE_WEB_CONFIG assente o non JSON. Proseguo ma Firebase potrebbe non inizializzarsi.');
  }

  const out = {
    FIREBASE: {
      enabled: FIREBASE_ENABLED,
      config: fbConfigObj
    },
    // alias minuscolo per compatibilità col vecchio codice
    firebase: {
      enabled: FIREBASE_ENABLED,
      config: fbConfigObj
    },
    REMINDER_DAYS_AHEAD,
    WHATSAPP_API_BASE,
    GOOGLE_CALENDAR_EMBED_URL,
    VERSION: buildVersion(),
    BUILD_AT: new Date().toISOString()
  };

  const dist = path.join(process.cwd(), 'config.js');
  const body =
`/* AUTO-GENERATED BY inject-env.cjs */
window.AppConfig = Object.freeze(${JSON.stringify(out, null, 2)});
`;
  fs.writeFileSync(dist, body, 'utf8');

  console.log('✅ Generato ./config.js');
} catch (e) {
  console.error('❌ inject-env error:', e);
  process.exit(1);
}
